package export;

import java.sql.ResultSetMetaData;
import java.sql.SQLException;

/**
 *
 * @author holanda
 */
public class ImportForm extends javax.swing.JPanel {

    /**
     * Creates new form ImportForm
     */
    public ImportForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        udfList = new javax.swing.JList<>();
        importButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sqlField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        String[] udfOptStrings = new String[0];
        String sql = "SELECT name FROM functions WHERE language >= 6 AND language <= 11;";

        try {
            String[] aux = new String[100];

            ConnectionGlobal.rs = ConnectionGlobal.st.executeQuery(sql);
            int i;
            for (i = 0; ConnectionGlobal.rs.next(); i++) {
                aux[i] =  ConnectionGlobal.rs.getString(1);
            }
            udfOptStrings = new String[i+1];
            for (int j = 0; j <=i ; j++ ){
                udfOptStrings[j] = aux[j];
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        final String[]  udfOptStrings_aux = udfOptStrings;
        udfList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = udfOptStrings_aux;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(udfList);

        importButton.setText("Import");

        sqlField.setColumns(20);
        sqlField.setRows(5);
        sqlField.setText("SELECT id, mean_deviation(value)\n            , variance(value)\nFROM data\nWHERE value > 1000");
        jScrollPane2.setViewportView(sqlField);

        jLabel1.setText("SQL Query:");

        jLabel2.setText("UDFs:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(importButton)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(268, 268, 268))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(importButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JButton importButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea sqlField;
    private javax.swing.JList<String> udfList;
    // End of variables declaration
}
